import { promises as fs } from "node:fs";
import path from "node:path";
import type {
  DocSource,
  ExtractedRule,
  OutputLeaf,
  OutputLeafFrontmatter,
} from "../types.js";
import type { LibraryImportMap } from "../link/import-grep.js";
import { leafPathForSource, topicSlugForSource } from "./paths.js";

function renderFrontmatter(fm: OutputLeafFrontmatter): string {
  const lines: string[] = ["---"];
  lines.push(`scope: ${fm.scope}`);
  if (fm.library) lines.push(`library: ${fm.library}`);
  lines.push(
    `applies_to: ${JSON.stringify(fm.applies_to)}`,
  );
  lines.push(`source_id: ${fm.source_id}`);
  lines.push(`source_uri: ${fm.source_uri}`);
  if (fm.source_url) lines.push(`source_url: ${fm.source_url}`);
  lines.push(`chunk_id: ${fm.chunk_id}`);
  lines.push(`extracted_at: ${fm.extracted_at}`);
  if (fm.rules.length > 0) {
    lines.push(`rules:`);
    for (const r of fm.rules) {
      lines.push(`  - modality: ${r.modality}`);
      lines.push(`    category: ${r.category}`);
      lines.push(
        `    text: ${JSON.stringify(r.text)}`,
      );
    }
  }
  lines.push("---");
  return lines.join("\n");
}

function renderBody(
  source: DocSource,
  rules: ExtractedRule[],
): string {
  const title = source.defaultLibraryName
    ? `Constraints — ${source.defaultLibraryName}`
    : `Constraints — ${source.id}`;
  const lines: string[] = [`# ${title}`, ""];
  if (rules.length === 0) {
    lines.push(
      `_No imperative rules were extracted from the source documentation._`,
    );
  } else {
    rules.forEach((rule, i) => {
      lines.push(`${i + 1}. ${rule.ruleText}`);
    });
  }
  lines.push("");
  lines.push(`## Source`);
  lines.push("");
  lines.push(`- Source URI: ${source.uri}`);
  if (source.sourceUrl) lines.push(`- URL: <${source.sourceUrl}>`);
  lines.push(`- Source ID: ${source.id}`);
  lines.push(`- Generated by: docs-ingest`);
  lines.push("");
  return lines.join("\n");
}

export interface EmitOptions {
  contextMapRoot: string;
  source: DocSource;
  rules: ExtractedRule[];
  importMap: LibraryImportMap | null;
  extractedAt: string;
  primaryDocPath?: string;
}

export interface EmittedLeaf {
  absolutePath: string;
  relativePath: string;
  ruleCount: number;
  appliesTo: string[];
}

export async function writeLeaf(opts: EmitOptions): Promise<EmittedLeaf> {
  const slug = topicSlugForSource(opts.source, opts.primaryDocPath);
  const absolutePath = leafPathForSource(
    opts.contextMapRoot,
    opts.source,
    slug,
  );
  const appliesTo = opts.importMap
    ? opts.importMap.globs
    : ["src/**/*.{ts,tsx,js,mjs,cjs}"];

  const fm: OutputLeafFrontmatter = {
    scope: opts.source.defaultScope,
    ...(opts.source.defaultLibraryName
      ? { library: opts.source.defaultLibraryName }
      : {}),
    applies_to: appliesTo,
    source_id: opts.source.id,
    source_uri: opts.source.uri,
    ...(opts.source.sourceUrl ? { source_url: opts.source.sourceUrl } : {}),
    chunk_id:
      opts.rules[0]?.chunkId ?? `${opts.source.id}:aggregate`,
    extracted_at: opts.extractedAt,
    rules: opts.rules.map((r) => ({
      modality: r.modality,
      category: r.category,
      text: r.ruleText,
    })),
  };
  const leaf: OutputLeaf = {
    relativePath: path.relative(opts.contextMapRoot, absolutePath),
    frontmatter: fm,
    body: renderBody(opts.source, opts.rules),
  };

  const fileText = `${renderFrontmatter(leaf.frontmatter)}\n\n${leaf.body}`;
  await fs.mkdir(path.dirname(absolutePath), { recursive: true });
  await fs.writeFile(absolutePath, fileText, "utf8");

  return {
    absolutePath,
    relativePath: leaf.relativePath,
    ruleCount: opts.rules.length,
    appliesTo,
  };
}
